
uhc: false
uhcMinHearts: 0
uhcMaxHearts: 60
giftHearts: false

ghoul: false
quests: false
assassins: false

blueLifeDecay: true
defaultLives: 3

singularenchanter: false

rewardCoords:
  x: 0
  y: 0
  z: 0
heartsReward: 20
questRewards:
  - "diamond:2-5"
  - "stick"
  - "tnt:2"